### ISSUE TITLE
Makefile

### ISSUE THREAD

**Issue by thiagocesar1** [ImmobilienScout24/kiosk-browser#13]
On run make in directory of kiosk-browser, i received this message:

fatal: Not a git repository (or any of the parent directories): .git

fatal: Not a git repository (or any of the parent directories): .git
-e
Error: All changes must be comitted!

Makefile:28: recipe for target 'checkstatus' failed

**Comment by schlomo** [comment]
Was this a `git clone`or a plain download? I never tried to work with a plain downloads. It might be that the code assumes that it always has a git repo.

**Comment by thiagocesar1** [comment]
Hi Schlomo, Thanks for reply, with plain download it didn't work, but with git clone the project was installed. Another question, how to disable the screen with network parameters before the kiosk-browser run?

**Comment by thiagocesar1** [comment]
Hi Schlomo, the problem is solved. Nice project, thanks for all.

**Comment by schlomo** [comment]
​How did you disable the info screen?​

**Comment by thiagocesar1** [comment]
In path /usr/share/kiosk-browser
In xsession.sh,I commented lines containing the messages. Down the line 39.

**Comment by thiagocesar1** [comment]
When i'm open  the epiphany browser in this kiosk browser, de address bar doesn't hide automatically, you have an idea about this?

**Comment by schlomo** [comment]
Feel free to provide a pull request defining a new variable that hides the
network info.

Epiphany and midori both have (in my experience) troubles hiding the
address bar. We use Google Chrome or Chromium so I did not spend so much
time testing with epiphany and other browsers. I only added support so that
I could play with them without damaging the working instances of
kiosk-browser.

Again pull requests with improvements are most welcome.

**Comment by thiagocesar1** [comment]
But this is my problem, i need to reproduce videos in html with browser in kiosk mode, but, on my searches, epiphany supports HTML5, besides reproduce videos with good performance. Chromium depends of ffmpeg to run videos, but he's not available to raspberry, so, i'll continue researching ways to play videos in html. Thanks for reply Mr. Schlomo.

**Comment by schlomo** [comment]
Oh, you run this also on the Pi :-)

Yes, as far as I know epiphany is indeed the only option for accelerated
video play back (https://www.raspberrypi.org/web-browser-released/)

Please let me know if you find a way to get epiphany full screen without
any controls.

**Comment by thiagocesar1** [comment]
I'm testing a way to play videos with OMXPlayer in the browser with a version of OMXPlayer done with PHP-Dbus, but the articles that are found in Chinese, should get some success, post a reply.

**Comment by schlomo** [comment]
If you *only* want to play back a full screen video (or many) then I would
really suggest you to use XBMC/Kodi:
http://blog.schlomo.schapiro.org/2014/05/simple-video-presentation.html

That will also support all kind of streaming media, of course.

**Comment by thiagocesar1** [comment]
Play videos is only part of the html page will show, that's the problem, run the browser in full screen, running html5 videos and others things in the page. Incorporate OMXPlayer in the browser would be the best solution to such problem.But this is not so simple.

**Comment by schlomo** [comment]
Sounds like quite a project. Maybe you will spend less time if you create a
screen recording of that and then simply play back the video?

In any case, please let me know what comes out of it. Also, in some places
we ended up using a Core i7 mini desktop instead of the Raspberry Pi to
have a kiosk system with lots of power behind it. The kiosk-browser package
works the same on Ubuntu :-)

**Comment by thiagocesar1** [comment]
Thanks for reply Mr. Schlomo, i'll post news if the tests succeed. Anyway, the omxplayer can run videos with a considerable quality. Since this is a static page if it runs as I imagine, it is enough that the project to be completed with success. This Kiosk browser will help me for sure.
