### ISSUE TITLE
Read-only filesystem

### ISSUE THREAD

**Issue by probonopd** [ImmobilienScout24/kiosk-browser#8]
Make filesystem read-only so that power can be cut off at any time without any danger to the system. E.g., a combination of overlayfs and squashfs could be used, as it is done in OpenWrt. http://wiki.openwrt.org/doc/techref/filesystems

**Comment by schlomo** [comment]
ATM kiosk-browser is intended to be used on a regular Ubuntu/Debian Linux distribution. The software maintenance model for those distros is to run package updates over a long period of time. kiosk-browser fits well into this model (our web terminals update every night).

Having a read-only file system would have to be implemented on the OS level, not in kiosk-browser. Since a couple of months ago kiosk-browser uses a temporary directory as a `HOME` directory so that kiosk-browser itself actually would also work if installed on a system with `/usr` mounted read-only. 

Of course, you would have to solve the software maintenance problem somehow differently.
